services:
  - type: web
    name: jaws-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 server:app
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TTS_VOICE
        value: en-GB-RyanNeural